# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('followee_id', models.BigIntegerField(db_index=True)),
                ('follow_date', models.DateTimeField(verbose_name=b'follow date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('text', models.CharField(default=b'', max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name=b'date_posted')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name=b'first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name=b'last name')),
            ],
        ),
    ]
