# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import matcher_pb2 as matcher__pb2


class RecommenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recommend = channel.unary_unary(
        '/recommender.Recommender/Recommend',
        request_serializer=matcher__pb2.WhichUser.SerializeToString,
        response_deserializer=matcher__pb2.UserList.FromString,
        )


class RecommenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Recommend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recommend': grpc.unary_unary_rpc_method_handler(
          servicer.Recommend,
          request_deserializer=matcher__pb2.WhichUser.FromString,
          response_serializer=matcher__pb2.UserList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'recommender.Recommender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
