# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matcher.proto',
  package='recommender',
  syntax='proto3',
  serialized_pb=_b('\n\rmatcher.proto\x12\x0brecommender\"\x1b\n\tWhichUser\x12\x0e\n\x06userID\x18\x01 \x01(\t\"1\n\x08UserList\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\x15\n\rrecommendedID\x18\x02 \x03(\t2K\n\x0bRecommender\x12<\n\tRecommend\x12\x16.recommender.WhichUser\x1a\x15.recommender.UserList\"\x00\x62\x06proto3')
)




_WHICHUSER = _descriptor.Descriptor(
  name='WhichUser',
  full_name='recommender.WhichUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='recommender.WhichUser.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)


_USERLIST = _descriptor.Descriptor(
  name='UserList',
  full_name='recommender.UserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='recommender.UserList.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recommendedID', full_name='recommender.UserList.recommendedID', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['WhichUser'] = _WHICHUSER
DESCRIPTOR.message_types_by_name['UserList'] = _USERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WhichUser = _reflection.GeneratedProtocolMessageType('WhichUser', (_message.Message,), dict(
  DESCRIPTOR = _WHICHUSER,
  __module__ = 'matcher_pb2'
  # @@protoc_insertion_point(class_scope:recommender.WhichUser)
  ))
_sym_db.RegisterMessage(WhichUser)

UserList = _reflection.GeneratedProtocolMessageType('UserList', (_message.Message,), dict(
  DESCRIPTOR = _USERLIST,
  __module__ = 'matcher_pb2'
  # @@protoc_insertion_point(class_scope:recommender.UserList)
  ))
_sym_db.RegisterMessage(UserList)



_RECOMMENDER = _descriptor.ServiceDescriptor(
  name='Recommender',
  full_name='recommender.Recommender',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=110,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='recommender.Recommender.Recommend',
    index=0,
    containing_service=None,
    input_type=_WHICHUSER,
    output_type=_USERLIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDER)

DESCRIPTOR.services_by_name['Recommender'] = _RECOMMENDER

# @@protoc_insertion_point(module_scope)
