# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import requester_pb2 as requester__pb2


class RecommenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Request = channel.unary_unary(
        '/requester.Recommender/Request',
        request_serializer=requester__pb2.WhichUser.SerializeToString,
        response_deserializer=requester__pb2.UserList.FromString,
        )


class RecommenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Request': grpc.unary_unary_rpc_method_handler(
          servicer.Request,
          request_deserializer=requester__pb2.WhichUser.FromString,
          response_serializer=requester__pb2.UserList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'requester.Recommender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
