# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requester.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='requester.proto',
  package='requester',
  syntax='proto3',
  serialized_pb=_b('\n\x0frequester.proto\x12\trequester\"\x1d\n\tWhichUser\x12\x10\n\x08serverID\x18\x01 \x01(\t\"-\n\x08UserList\x12!\n\x02ua\x18\x01 \x03(\x0b\x32\x15.requester.UserAnswer\"?\n\nUserAnswer\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12!\n\x06\x61nswer\x18\x02 \x03(\x0b\x32\x11.requester.Answer\"3\n\x06\x41nswer\x12\x13\n\x0bwhichLabels\x18\x02 \x01(\t\x12\x14\n\x0clabelRatings\x18\x03 \x01(\t2E\n\x0bRecommender\x12\x36\n\x07Request\x12\x14.requester.WhichUser\x1a\x13.requester.UserList\"\x00\x62\x06proto3')
)




_WHICHUSER = _descriptor.Descriptor(
  name='WhichUser',
  full_name='requester.WhichUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverID', full_name='requester.WhichUser.serverID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)


_USERLIST = _descriptor.Descriptor(
  name='UserList',
  full_name='requester.UserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ua', full_name='requester.UserList.ua', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=106,
)


_USERANSWER = _descriptor.Descriptor(
  name='UserAnswer',
  full_name='requester.UserAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='requester.UserAnswer.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='requester.UserAnswer.answer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=171,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='requester.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whichLabels', full_name='requester.Answer.whichLabels', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labelRatings', full_name='requester.Answer.labelRatings', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=224,
)

_USERLIST.fields_by_name['ua'].message_type = _USERANSWER
_USERANSWER.fields_by_name['answer'].message_type = _ANSWER
DESCRIPTOR.message_types_by_name['WhichUser'] = _WHICHUSER
DESCRIPTOR.message_types_by_name['UserList'] = _USERLIST
DESCRIPTOR.message_types_by_name['UserAnswer'] = _USERANSWER
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WhichUser = _reflection.GeneratedProtocolMessageType('WhichUser', (_message.Message,), dict(
  DESCRIPTOR = _WHICHUSER,
  __module__ = 'requester_pb2'
  # @@protoc_insertion_point(class_scope:requester.WhichUser)
  ))
_sym_db.RegisterMessage(WhichUser)

UserList = _reflection.GeneratedProtocolMessageType('UserList', (_message.Message,), dict(
  DESCRIPTOR = _USERLIST,
  __module__ = 'requester_pb2'
  # @@protoc_insertion_point(class_scope:requester.UserList)
  ))
_sym_db.RegisterMessage(UserList)

UserAnswer = _reflection.GeneratedProtocolMessageType('UserAnswer', (_message.Message,), dict(
  DESCRIPTOR = _USERANSWER,
  __module__ = 'requester_pb2'
  # @@protoc_insertion_point(class_scope:requester.UserAnswer)
  ))
_sym_db.RegisterMessage(UserAnswer)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'requester_pb2'
  # @@protoc_insertion_point(class_scope:requester.Answer)
  ))
_sym_db.RegisterMessage(Answer)



_RECOMMENDER = _descriptor.ServiceDescriptor(
  name='Recommender',
  full_name='requester.Recommender',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=226,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='Request',
    full_name='requester.Recommender.Request',
    index=0,
    containing_service=None,
    input_type=_WHICHUSER,
    output_type=_USERLIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDER)

DESCRIPTOR.services_by_name['Recommender'] = _RECOMMENDER

# @@protoc_insertion_point(module_scope)
